//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebArrCalc.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/ArrayCalc")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ResField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Res {
            get {
                return this.ResField;
            }
            set {
                if ((this.ResField.Equals(value) != true)) {
                    this.ResField = value;
                    this.RaisePropertyChanged("Res");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICalcController")]
    public interface ICalcController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcController/Mean", ReplyAction="http://tempuri.org/ICalcController/MeanResponse")]
        WebArrCalc.ServiceReference1.Result Mean(string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcController/Mean", ReplyAction="http://tempuri.org/ICalcController/MeanResponse")]
        System.Threading.Tasks.Task<WebArrCalc.ServiceReference1.Result> MeanAsync(string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcController/Sum", ReplyAction="http://tempuri.org/ICalcController/SumResponse")]
        WebArrCalc.ServiceReference1.Result Sum(string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcController/Sum", ReplyAction="http://tempuri.org/ICalcController/SumResponse")]
        System.Threading.Tasks.Task<WebArrCalc.ServiceReference1.Result> SumAsync(string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcController/Mul", ReplyAction="http://tempuri.org/ICalcController/MulResponse")]
        WebArrCalc.ServiceReference1.Result Mul(string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcController/Mul", ReplyAction="http://tempuri.org/ICalcController/MulResponse")]
        System.Threading.Tasks.Task<WebArrCalc.ServiceReference1.Result> MulAsync(string a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcControllerChannel : WebArrCalc.ServiceReference1.ICalcController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcControllerClient : System.ServiceModel.ClientBase<WebArrCalc.ServiceReference1.ICalcController>, WebArrCalc.ServiceReference1.ICalcController {
        
        public CalcControllerClient() {
        }
        
        public CalcControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebArrCalc.ServiceReference1.Result Mean(string a) {
            return base.Channel.Mean(a);
        }
        
        public System.Threading.Tasks.Task<WebArrCalc.ServiceReference1.Result> MeanAsync(string a) {
            return base.Channel.MeanAsync(a);
        }
        
        public WebArrCalc.ServiceReference1.Result Sum(string a) {
            return base.Channel.Sum(a);
        }
        
        public System.Threading.Tasks.Task<WebArrCalc.ServiceReference1.Result> SumAsync(string a) {
            return base.Channel.SumAsync(a);
        }
        
        public WebArrCalc.ServiceReference1.Result Mul(string a) {
            return base.Channel.Mul(a);
        }
        
        public System.Threading.Tasks.Task<WebArrCalc.ServiceReference1.Result> MulAsync(string a) {
            return base.Channel.MulAsync(a);
        }
    }
}
